### ISSUE TITLE
Request...

### ISSUE THREAD

**Issue by Se7Touch** [mac-user669/ZenithDark#6]
Hi, I like so much this tweak. But I want a fully dark option. Can you add a switchable dark mode ? Ex. Blurred Dark - OLED

**Comment by mac-user669** [comment]
Hey, glad you like the tweak! I’ve been working on trying to implement more colors in, so stay tuned. Thanks!

**Comment by Se7Touch** [comment]
I thank you. I wish you good work. 😊

**Comment by mac-user669** [comment]
Could you try ZenithDarkBeta 1.3.1 from https://mac-user669.github.io/beta/? It has an OLED mode, and an OLED adaptive mode. Thanks!

**Comment by Se7Touch** [comment]
i tested a beta version and suprise all mode working perfectly :) Thank you 😊

**Comment by mac-user669** [comment]
Awesome! I’m going to make a few changes to it, and then it’ll be out on my main repo. Thanks!
